---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# aquametNWCA

The goal of aquametNWCA is to calculate vegetation metrics and the Vegetation Multimetric Index (VMMI) for EPA's National Wetlands Condition Assessment (NWCA). The calculations of metrics and VMMI scores are based on the 2011 survey. Calculations are currently based on use of the taxa lists as utilized for the NWCA 2011 report. This includes taxonomic information, Coefficients of Conservatism, native status, and Wetland Indicator Status as assigned in 2011. Detailed information on expected fields in input data frames is provided in help files for functions, and examples of how to use functions together are provided in vignettes as part of the package documentation. In addition, there are PDF files containing metric descriptions for each set of metrics calculated. 

## Disclaimer

The United States Environmental Protection Agency (EPA) R package code is provided on an "as is" basis and the user assumes responsibility for its use.  EPA has relinquished control of the information and no longer has responsibility to protect the integrity , confidentiality, or availability of the information.  Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by EPA.  The EPA seal and logo shall not be used in any manner to imply endorsement of any commercial product or activity by EPA or the United States Government.

